{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# OSAP Nivel 2 \u2014 CORREGIDO (decay + placebo + capacidad)\n\n",
    "Bug arreglado: el headline usa PredictorLSretWide (todas las senales, no 12).\n",
    "Decay reportado en cambio absoluto (pp/mes), robusto a denominadores ~0.\n\n",
    "Mover a Mi unidad/OSAP: SignalDoc.csv, PredictorLSretWide.csv, PredictorPortsFull.csv, ",
    "PlaceboPortsFull.csv, los 4 HoldPer.zip y los 3 LiqScreen.zip.\n\n",
    "NOTA: este notebook cubre DECAY (que funciona). El CICLO va en el notebook Comomentum_WRDS."
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 1 -- montar Mi unidad y comprobar archivos\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "import os\n",
    "DATA_DIR = '/content/drive/MyDrive/OSAP'   # <-- carpeta en Mi unidad\n",
    "\n",
    "assert os.path.isdir(DATA_DIR), f'No existe {DATA_DIR}. Crea la carpeta OSAP en Mi unidad.'\n",
    "print('Archivos en OSAP:')\n",
    "for f in sorted(os.listdir(DATA_DIR)):\n",
    "    p = os.path.join(DATA_DIR, f)\n",
    "    sz = os.path.getsize(p)/1e6 if os.path.isfile(p) else 0\n",
    "    print(f'   {f}   ({sz:.1f} MB)')\n",
    "\n",
    "# obligatorios (Nivel 1 + control placebo + patas separadas)\n",
    "need = ['SignalDoc.csv', 'PredictorLSretWide.csv', 'PredictorPortsFull.csv', 'PlaceboPortsFull.csv']\n",
    "miss = [f for f in need if not os.path.isfile(os.path.join(DATA_DIR, f))]\n",
    "assert not miss, f'Faltan archivos obligatorios: {miss}'\n",
    "\n",
    "# opcionales: ejes de capacidad (holding period y liquidez). Se usan si estan.\n",
    "HOLD_ZIPS = {h: f'PredictorAltPorts_HoldPer_{h}.zip' for h in [1,3,6,12]}\n",
    "LIQ_ZIPS  = {'NYSEonly':'PredictorAltPorts_LiqScreen_NYSEonly.zip',\n",
    "             'Price_gt_5':'PredictorAltPorts_LiqScreen_Price_gt_5.zip',\n",
    "             'ME_gt_NYSE20pct':'PredictorAltPorts_LiqScreen_ME_gt_NYSE20pct.zip'}\n",
    "have_hold = {k:v for k,v in HOLD_ZIPS.items() if os.path.isfile(os.path.join(DATA_DIR,v))}\n",
    "have_liq  = {k:v for k,v in LIQ_ZIPS.items()  if os.path.isfile(os.path.join(DATA_DIR,v))}\n",
    "print('\\nHolding-period zips disponibles:', list(have_hold.keys()))\n",
    "print('Liquidity-screen zips disponibles:', list(have_liq.keys()))\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 2 -- imports + helpers\n",
    "import numpy as np, pandas as pd, scipy.stats as st\n",
    "import zipfile, io\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import rcParams\n",
    "rcParams.update({'font.family':'serif','font.size':9,'axes.linewidth':0.6,\n",
    "                 'axes.spines.top':False,'axes.spines.right':False,\n",
    "                 'figure.dpi':140,'savefig.dpi':200})\n",
    "np.random.seed(0)\n",
    "\n",
    "def parse_ym(x):\n",
    "    s = str(x)\n",
    "    if 'm' in s:\n",
    "        y,m = s.split('m'); return pd.Timestamp(int(y), int(m), 1)\n",
    "    return pd.to_datetime(s, errors='coerce')\n",
    "\n",
    "def normalize_long(df):\n",
    "    \"\"\"Lleva cualquier tabla de retornos a columnas: date, signal, ret (largo).\"\"\"\n",
    "    cols = {c.lower():c for c in df.columns}\n",
    "    date_c = cols.get('date', df.columns[0])\n",
    "    if 'signalname' in cols and 'ret' in cols:       # ya es largo, una pata = LS\n",
    "        out = df.rename(columns={cols['signalname']:'signal', cols['ret']:'ret', date_c:'date'})\n",
    "        return out[['date','signal','ret']].copy()\n",
    "    # formato ancho: date + una columna por senal\n",
    "    wide = df.rename(columns={date_c:'date'})\n",
    "    return wide.melt(id_vars='date', var_name='signal', value_name='ret')\n",
    "\n",
    "def long_short_from_portsfull(df):\n",
    "    \"\"\"De PredictorPortsFull (date,signalname,port,ret) saca el spread LS por senal:\n",
    "       port mas alto menos port mas bajo (las dos puntas de la ordenacion).\"\"\"\n",
    "    cols = {c.lower():c for c in df.columns}\n",
    "    d = df.rename(columns={cols.get('signalname','signalname'):'signal',\n",
    "                           cols.get('port','port'):'port',\n",
    "                           cols.get('ret','ret'):'ret',\n",
    "                           cols.get('date','date'):'date'})\n",
    "    d = d[['date','signal','port','ret']].dropna(subset=['ret'])\n",
    "    # 'port' puede ser numerico (1..N) o etiquetas tipo '01','10','LS'. Si hay 'LS', usalo.\n",
    "    def spread(group):\n",
    "        ports = group['port'].astype(str)\n",
    "        if (ports=='LS').any():\n",
    "            return group.loc[ports=='LS','ret']\n",
    "        # si no, top - bottom por orden de 'port'\n",
    "        g = group.copy(); g['pnum'] = pd.to_numeric(g['port'], errors='coerce')\n",
    "        g = g.dropna(subset=['pnum'])\n",
    "        if g.empty: return pd.Series(dtype=float)\n",
    "        lo, hi = g.pnum.min(), g.pnum.max()\n",
    "        top = g[g.pnum==hi].set_index('date')['ret']\n",
    "        bot = g[g.pnum==lo].set_index('date')['ret']\n",
    "        return (top - bot)\n",
    "    # construir LS por (signal,date)\n",
    "    recs=[]\n",
    "    for sig, grp in d.groupby('signal'):\n",
    "        ls = spread(grp.assign(signal=sig))\n",
    "        if len(ls):\n",
    "            tmp = ls.reset_index(); tmp.columns=['date','ret']; tmp['signal']=sig\n",
    "            recs.append(tmp)\n",
    "    out = pd.concat(recs, ignore_index=True) if recs else pd.DataFrame(columns=['date','signal','ret'])\n",
    "    return out\n",
    "\n",
    "def read_zip_returns(path):\n",
    "    \"\"\"Abre un .zip de AltPorts y concatena todos los CSV de retornos que contenga,\n",
    "       devolviendo LS por senal. Maneja subcarpetas (Original_Cuts, etc.).\"\"\"\n",
    "    frames=[]\n",
    "    with zipfile.ZipFile(path) as z:\n",
    "        csvs = [n for n in z.namelist() if n.lower().endswith('.csv')]\n",
    "        # preferir la carpeta Original_Cuts (sin VW) si existe, para comparar manzanas con manzanas\n",
    "        pref = [n for n in csvs if 'original_cuts' in n.lower() and 'vw' not in n.lower()]\n",
    "        use = pref if pref else csvs\n",
    "        for n in use:\n",
    "            with z.open(n) as fh:\n",
    "                try:\n",
    "                    df = pd.read_csv(fh)\n",
    "                except Exception:\n",
    "                    continue\n",
    "            if 'port' in [c.lower() for c in df.columns]:\n",
    "                ls = long_short_from_portsfull(df)\n",
    "            else:\n",
    "                ls = normalize_long(df)\n",
    "            if len(ls): frames.append(ls)\n",
    "    if not frames: return pd.DataFrame(columns=['date','signal','ret'])\n",
    "    out = pd.concat(frames, ignore_index=True)\n",
    "    out = out.groupby(['date','signal'], as_index=False)['ret'].mean()  # dedup si varias cuts\n",
    "    return out\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 3 -- metadatos + funcion de regimenes\n",
    "doc = pd.read_csv(os.path.join(DATA_DIR, 'SignalDoc.csv'))\n",
    "doc = doc[doc['Cat.Signal'] == 'Predictor'].copy()\n",
    "doc['Acronym'] = doc['Acronym'].str.strip()\n",
    "meta = doc[['Acronym','Year','SampleEndYear']].dropna()\n",
    "meta = meta.rename(columns={'Acronym':'signal','Year':'PubYear','SampleEndYear':'SampleEnd'})\n",
    "meta['PubYear']=meta.PubYear.astype(int); meta['SampleEnd']=meta.SampleEnd.astype(int)\n",
    "print(f'{len(meta)} predictores con anyo de publicacion y fin de muestra')\n",
    "\n",
    "def build_regimes(long, meta):\n",
    "    long = long.dropna(subset=['ret']).copy()\n",
    "    long['date'] = long['date'].map(parse_ym)\n",
    "    long['signal'] = long['signal'].str.strip()\n",
    "    long = long.dropna(subset=['date'])\n",
    "    long['year'] = long.date.dt.year\n",
    "    df = long.merge(meta, on='signal', how='inner').sort_values(['signal','date'])\n",
    "    def reg(r):\n",
    "        if r.year <= r.SampleEnd: return 'in_sample'\n",
    "        if r.year <= r.PubYear:   return 'post_sample'\n",
    "        return 'post_pub'\n",
    "    df['regime'] = df.apply(reg, axis=1)\n",
    "    scale = 1.0 if df.ret.abs().median() < 0.05 else 0.01\n",
    "    df['ret_dec'] = df.ret * scale\n",
    "    return df\n",
    "\n",
    "def decay_stats(df, label):\n",
    "    g = df.groupby(['signal','regime'])['ret_dec'].mean().reset_index()\n",
    "    piv = g.pivot(index='signal', columns='regime', values='ret_dec').dropna(subset=['in_sample','post_pub'])\n",
    "    ins, post = piv['in_sample'].values, piv['post_pub'].values\n",
    "    abs_decay = ins.mean() - post.mean()                 # cambio absoluto (robusto)\n",
    "    # fraccion solo si el edge in-sample medio es claramente positivo\n",
    "    frac = abs_decay/ins.mean() if ins.mean() > 0.001 else np.nan\n",
    "    tt = st.ttest_rel(ins, post)\n",
    "    fr_txt = f'{frac*100:.1f}%' if not np.isnan(frac) else 'n/a'\n",
    "    print(f'[{label}] n={len(piv)}  in={ins.mean()*100:.3f}%  post={post.mean()*100:.3f}%  '\n",
    "          f'abs_decay={abs_decay*100:.3f}pp  frac={fr_txt}  t={tt.statistic:.2f} p={tt.pvalue:.1e}')\n",
    "    return dict(label=label, n=len(piv), edge_in=ins.mean(), edge_post=post.mean(),\n",
    "                abs_decay=abs_decay, decay_frac=frac, t=tt.statistic, p=tt.pvalue, piv=piv)\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 4 -- EXP A: decay headline (usar LSretWide: limpio, todas las senales)\n",
    "ls_main = normalize_long(pd.read_csv(os.path.join(DATA_DIR,'PredictorLSretWide.csv')))\n",
    "dfA = build_regimes(ls_main, meta)\n",
    "A = decay_stats(dfA, 'PRED headline')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 5 -- EXP B: PLACEBO control (no debe haber decay)\n",
    "pl = pd.read_csv(os.path.join(DATA_DIR,'PlaceboPortsFull.csv'))\n",
    "ls_pl = long_short_from_portsfull(pl) if 'port' in [c.lower() for c in pl.columns] else normalize_long(pl)\n",
    "# los placebos no tienen Year/SampleEnd propios; usamos el calendario medio de predictores\n",
    "# (control: aplicamos las MISMAS ventanas temporales medias). Construimos pseudo-meta.\n",
    "pub_med = int(meta.PubYear.median()); end_med = int(meta.SampleEnd.median())\n",
    "meta_pl = pd.DataFrame({'signal': ls_pl['signal'].unique()})\n",
    "meta_pl['PubYear']=pub_med; meta_pl['SampleEnd']=end_med\n",
    "dfB = build_regimes(ls_pl, meta_pl)\n",
    "B = decay_stats(dfB, 'PLACEBO')\n",
    "print(f'  -> control OK si el decay del placebo es ~0 y NO significativo')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 6 -- EXP C: REVIVAL / ciclo (unico del paper), sobre predictores\n",
    "def revival_test(df, label):\n",
    "    post_df = df[df.regime=='post_pub']\n",
    "    rows=[]\n",
    "    for s, sub in post_df.groupby('signal'):\n",
    "        sub=sub.sort_values('date')\n",
    "        if len(sub)<72: continue\n",
    "        e=sub['ret_dec'].rolling(36).mean().dropna().values\n",
    "        if len(e)<24: continue\n",
    "        med=np.median(e); lo,hi=[],[]\n",
    "        for t in range(len(e)-12):\n",
    "            (lo if e[t]<med else hi).append(e[t+12])\n",
    "        if lo and hi: rows.append((s,np.mean(lo),np.mean(hi)))\n",
    "    rev=pd.DataFrame(rows,columns=['signal','after_crowded','after_slack'])\n",
    "    tt=st.ttest_rel(rev['after_crowded'],rev['after_slack'])\n",
    "    fr=(rev.after_crowded>rev.after_slack).mean()\n",
    "    print(f'[{label}] revival n={len(rev)}  after_crowded={rev.after_crowded.mean()*100:.3f}%  '\n",
    "          f'after_slack={rev.after_slack.mean()*100:.3f}%  t={tt.statistic:.2f} p={tt.pvalue:.1e}  frac={fr*100:.0f}%')\n",
    "    return dict(label=label,n=len(rev),ac=rev.after_crowded.mean(),as_=rev.after_slack.mean(),\n",
    "                t=tt.statistic,p=tt.pvalue,frac=fr,rev=rev)\n",
    "C = revival_test(dfA,'PRED')\n",
    "Cpl = revival_test(dfB,'PLACEBO')   # el placebo tampoco debe revivir\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 7 -- EXP D: CAPACIDAD = escala de despliegue (phase diagram real)\n",
    "# La teoria predice: menos capacidad -> mas decay. Holding corto y screens\n",
    "# restrictivos = menos capacidad efectiva. Medimos decay_frac por nivel.\n",
    "cap_rows=[]\n",
    "# eje holding period (1<3<6<12 meses; holding corto = mas turnover = menos capacidad)\n",
    "for h, fn in have_hold.items():\n",
    "    ls = read_zip_returns(os.path.join(DATA_DIR, fn))\n",
    "    if len(ls)==0:\n",
    "        print('  (vacio)', fn); continue\n",
    "    dfh = build_regimes(ls, meta)\n",
    "    r = decay_stats(dfh, f'HoldPer_{h}')\n",
    "    cap_rows.append(('hold', h, r['abs_decay'], r['n']))\n",
    "# eje liquidez (mas restrictivo = menos capacidad). orden aproximado de severidad:\n",
    "liq_order = {'Price_gt_5':1,'NYSEonly':2,'ME_gt_NYSE20pct':3}\n",
    "for k, fn in have_liq.items():\n",
    "    ls = read_zip_returns(os.path.join(DATA_DIR, fn))\n",
    "    if len(ls)==0:\n",
    "        print('  (vacio)', fn); continue\n",
    "    dfl = build_regimes(ls, meta)\n",
    "    r = decay_stats(dfl, f'Liq_{k}')\n",
    "    cap_rows.append(('liq', liq_order.get(k,9), r['abs_decay'], r['n']))\n",
    "cap = pd.DataFrame(cap_rows, columns=['axis','level','abs_decay','n'])\n",
    "print('\\nCapacidad vs decay absoluto (pp/mes):')\n",
    "print(cap.to_string())\n",
    "hold = cap[cap.axis=='hold'].sort_values('level')\n",
    "if len(hold)>=3:\n",
    "    rho,pr = st.spearmanr(hold.level, hold.abs_decay)\n",
    "    print(f'Spearman(holding period, abs_decay) = {rho:.2f} (p={pr:.2f})  '\n",
    "          f'[esperado <0: holding largo=mas capacidad=menos decay]')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 8 -- FIGURAS\n",
    "# Fig A: decay event-time, predictores vs placebo\n",
    "for d,lab,col in [(dfA,'predictors','0.1'),(dfB,'placebo','0.55')]:\n",
    "    d['rel']=d.year-d.PubYear\n",
    "    prof=(d[d.rel.between(-10,10)].groupby('rel')['ret_dec'].mean()*100)\n",
    "    plt.plot(prof.index,prof.values,marker='o',ms=2.5,mfc='white',mew=0.6,color=col,label=lab)\n",
    "plt.axvline(0,color='0.5',ls='--',lw=0.9); plt.axhline(0,color='0.7',lw=0.6)\n",
    "plt.xlabel('anyos relativos a publicacion'); plt.ylabel('edge L-S medio (%/mes)')\n",
    "plt.legend(fontsize=7,frameon=False); plt.title('Decay: predictores vs placebo',fontsize=9,loc='left')\n",
    "plt.tight_layout(); plt.savefig('/content/real_fig_decay.pdf'); plt.show()\n",
    "\n",
    "# Fig B: revival scatter\n",
    "rev=C['rev']\n",
    "lim=[min(rev.after_crowded.min(),rev.after_slack.min())*100,\n",
    "     max(rev.after_crowded.max(),rev.after_slack.max())*100]\n",
    "plt.plot(lim,lim,color='0.6',ls='--',lw=0.9)\n",
    "plt.scatter(rev.after_slack*100,rev.after_crowded*100,s=14,facecolors='white',edgecolors='0.1',linewidths=0.7)\n",
    "plt.xlabel('edge tras ventana slack (%/mes)'); plt.ylabel('edge tras ventana crowded (%/mes)')\n",
    "plt.title('Revival: crowded -> edge mayor',fontsize=9,loc='left')\n",
    "plt.tight_layout(); plt.savefig('/content/real_fig_revival.pdf'); plt.show()\n",
    "\n",
    "# Fig C: capacidad vs decay (phase diagram real)\n",
    "if len(cap):\n",
    "    fig,ax=plt.subplots(figsize=(3.6,2.6))\n",
    "    for axis,mk,col in [('hold','o','0.1'),('liq','s','0.5')]:\n",
    "        sub=cap[cap.axis==axis].sort_values('level')\n",
    "        if len(sub): ax.plot(sub.level,sub.abs_decay*100,marker=mk,color=col,\n",
    "                             mfc='white',mew=0.6,label=axis)\n",
    "    ax.set_xlabel('escala de capacidad (nivel)'); ax.set_ylabel('decay post-pub (pp/mes)')\n",
    "    ax.legend(fontsize=7,frameon=False); ax.set_title('Capacidad vs decay',fontsize=9,loc='left')\n",
    "    plt.tight_layout(); plt.savefig('/content/real_fig_capacity.pdf'); plt.show()\n",
    "print('figuras guardadas en /content')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 9 -- RESULTS BLOCK (copiame TODO)\n",
    "print('='*64); print('PEGAME ESTE BLOQUE ENTERO'); print('='*64)\n",
    "print(f'N_signals_total          = {len(meta)}')\n",
    "print(f'PRED_n_decay             = {A[\"n\"]}')\n",
    "print(f'PRED_edge_in_pctmo       = {A[\"edge_in\"]*100:.4f}')\n",
    "print(f'PRED_edge_post_pctmo     = {A[\"edge_post\"]*100:.4f}')\n",
    "print(f'PRED_abs_decay_pp        = {A[\"abs_decay\"]*100:.3f}')\n",
    "print(f'PRED_decay_t             = {A[\"t\"]:.3f}')\n",
    "print(f'PRED_decay_p             = {A[\"p\"]:.3e}')\n",
    "print(f'PLACEBO_n_decay          = {B[\"n\"]}')\n",
    "print(f'PLACEBO_abs_decay_pp     = {B[\"abs_decay\"]*100:.3f}')\n",
    "print(f'PLACEBO_decay_t          = {B[\"t\"]:.3f}')\n",
    "print(f'PLACEBO_decay_p          = {B[\"p\"]:.3e}')\n",
    "print(f'PRED_revival_n           = {C[\"n\"]}')\n",
    "print(f'PRED_after_crowded_pctmo = {C[\"ac\"]*100:.4f}')\n",
    "print(f'PRED_after_slack_pctmo   = {C[\"as_\"]*100:.4f}')\n",
    "print(f'PRED_revival_t           = {C[\"t\"]:.3f}')\n",
    "print(f'PRED_revival_p           = {C[\"p\"]:.3e}')\n",
    "print(f'PRED_frac_reviving_pct   = {C[\"frac\"]*100:.1f}')\n",
    "print(f'PLACEBO_revival_t        = {Cpl[\"t\"]:.3f}')\n",
    "print(f'PLACEBO_revival_p        = {Cpl[\"p\"]:.3e}')\n",
    "print('CAPACITY_table (axis,level,decay_pct,n):')\n",
    "for _,r in cap.iterrows():\n",
    "    print(f'   {r.axis},{int(r.level)},{r.abs_decay*100:.3f},{int(r.n)}')\n",
    "print(f'data_release             = OSAP_Oct2025')\n",
    "print('='*64)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}