{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Comomentum sobre datos Stooq (GRATIS, sin WRDS)\n\n",
    "**Valida el CICLO del paper** sin esperar WRDS. Comomentum bajo -> momentum estable; ",
    "comomentum alto -> reversion (ciclo). Es tu diagrama de fases sobre datos reales.\n\n",
    "## Antes de correr (descarga manual de una vez):\n",
    "1. Ve a https://stooq.com/db/h/ -> fila **U.S.**, columna **ASCII**, periodo **Daily** -> descarga **d_us_txt.zip** (pide CAPTCHA, ~300 MB).\n",
    "2. Sube ese zip a **Mi unidad/STOOQ/** (sin descomprimir).\n",
    "3. Corre las celdas en orden. Pega el RESULTS BLOCK (Celda 9) y sube los 2 PDF de /content.\n\n",
    "Cuando llegue WRDS, el notebook Comomentum_WRDS hace lo mismo con CRSP (mejor calidad)."
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 1 -- montar Drive y localizar el ZIP de Stooq\n",
    "# ANTES DE CORRER:\n",
    "#  1. Ve a https://stooq.com/db/h/  -> fila U.S., columna ASCII, Daily -> descarga d_us_txt.zip\n",
    "#     (pide un CAPTCHA; es una descarga manual de una vez, ~300 MB)\n",
    "#  2. Sube d_us_txt.zip a una carpeta en Mi unidad, p.ej. Mi unidad/STOOQ/\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "import os\n",
    "STOOQ_DIR = '/content/drive/MyDrive/STOOQ'     # <-- carpeta donde subiste el zip\n",
    "ZIP_NAME  = 'd_us_txt.zip'\n",
    "zip_path = os.path.join(STOOQ_DIR, ZIP_NAME)\n",
    "assert os.path.isfile(zip_path), f'No encuentro {zip_path}. Sube d_us_txt.zip a {STOOQ_DIR}'\n",
    "print('ZIP encontrado:', zip_path, f'({os.path.getsize(zip_path)/1e6:.0f} MB)')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 2 -- imports + parametros\n",
    "import numpy as np, pandas as pd, scipy.stats as st\n",
    "import zipfile, io\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import rcParams\n",
    "rcParams.update({'font.family':'serif','font.size':9,'axes.linewidth':0.6,\n",
    "                 'axes.spines.top':False,'axes.spines.right':False,\n",
    "                 'figure.dpi':140,'savefig.dpi':200})\n",
    "np.random.seed(0)\n",
    "\n",
    "PRICE_MIN   = 5.0      # excluir precio < $5 (Lou-Polk)\n",
    "N_DECILES   = 10\n",
    "FORM_MONTHS = 12       # ventana de formacion\n",
    "SKIP        = 1        # saltar el mes mas reciente\n",
    "TOP_LIQUID  = 1500     # universo: las N mas liquidas cada mes (senal sin tardar horas)\n",
    "START_YEAR  = 1990     # Stooq US tiene buena cobertura desde ~1990\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 3 -- leer todos los .txt de acciones US del zip -> panel diario\n",
    "# estructura: data/daily/us/<nasdaq|nyse|nysemkt> stocks/<n>/<ticker>.us.txt\n",
    "frames = []\n",
    "with zipfile.ZipFile(zip_path) as z:\n",
    "    names = [n for n in z.namelist()\n",
    "             if n.endswith('.txt') and '/us/' in n.lower() and 'stocks' in n.lower()]\n",
    "    print('ficheros de acciones US:', len(names))\n",
    "    for i, n in enumerate(names):\n",
    "        try:\n",
    "            raw = z.read(n)\n",
    "            if len(raw) < 50:   # vacio\n",
    "                continue\n",
    "            d = pd.read_csv(io.BytesIO(raw))\n",
    "            d.columns = [c.strip('<>').lower() for c in d.columns]\n",
    "            if 'close' not in d.columns or 'date' not in d.columns:\n",
    "                continue\n",
    "            d = d[['ticker','date','close','vol']].copy()\n",
    "            frames.append(d)\n",
    "        except Exception:\n",
    "            continue\n",
    "        if i % 1000 == 0:\n",
    "            print(f'  {i}/{len(names)}', end='\\r')\n",
    "px = pd.concat(frames, ignore_index=True)\n",
    "px['date'] = pd.to_datetime(px['date'].astype(str), format='%Y%m%d', errors='coerce')\n",
    "px['ticker'] = px['ticker'].str.replace('.US','',regex=False).str.upper()\n",
    "px = px.dropna(subset=['date','close'])\n",
    "px = px[px['date'].dt.year >= START_YEAR]\n",
    "px['dollar_vol'] = px['close']*px['vol'].fillna(0)\n",
    "print('\\npanel diario:', px.shape, '| tickers:', px.ticker.nunique(),\n",
    "      '| span:', px.date.dt.year.min(), '-', px.date.dt.year.max())\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 4 -- retornos mensuales y semanales\n",
    "px = px.sort_values(['ticker','date'])\n",
    "# mensual: ultimo close del mes\n",
    "px['ym'] = px['date'].dt.to_period('M')\n",
    "monthly = (px.groupby(['ticker','ym'])\n",
    "             .agg(close=('close','last'), dvol=('dollar_vol','mean')).reset_index())\n",
    "monthly['ret'] = monthly.groupby('ticker')['close'].pct_change()\n",
    "monthly = monthly.dropna(subset=['ret'])\n",
    "# semanal: ultimo close de la semana -> retorno\n",
    "px['yw'] = px['date'].dt.to_period('W')\n",
    "weekly = (px.groupby(['ticker','yw']).agg(close=('close','last')).reset_index())\n",
    "weekly['ret'] = weekly.groupby('ticker')['close'].pct_change()\n",
    "weekly = weekly.dropna(subset=['ret'])\n",
    "print('mensual:', monthly.shape, '| semanal:', weekly.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 5 -- momentum decile cada mes sobre universo liquido\n",
    "m = monthly.copy()\n",
    "m['logret'] = np.log1p(m['ret'].clip(-0.95, 5))\n",
    "m['mom'] = (m.groupby('ticker')['logret']\n",
    "              .rolling(FORM_MONTHS, min_periods=FORM_MONTHS).sum()\n",
    "              .shift(SKIP).reset_index(level=0, drop=True))\n",
    "# filtro liquidez: top N por dollar-vol y precio>=5, cada mes (sin groupby.apply)\n",
    "m = m[(m.close >= PRICE_MIN) & m.mom.notna()].copy()\n",
    "m['dvol_rank'] = m.groupby('ym')['dvol'].rank(method='first', ascending=False)\n",
    "m = m[m['dvol_rank'] <= TOP_LIQUID].copy()\n",
    "m['decile'] = (m.groupby('ym')['mom']\n",
    "                 .transform(lambda x: pd.qcut(x, N_DECILES, labels=False, duplicates='drop')+1))\n",
    "print('panel con decil (universo liquido):', m.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 6 -- COMOMENTUM: corr media de pares semanal en winner y loser\n",
    "def pair_corr(tickers, wk_win, max_names=120):\n",
    "    sub = wk_win[wk_win.ticker.isin(tickers)]\n",
    "    piv = sub.pivot_table(index='yw', columns='ticker', values='ret')\n",
    "    piv = piv.dropna(axis=1, thresh=int(0.6*len(piv)))\n",
    "    if piv.shape[1] < 10: return np.nan\n",
    "    if piv.shape[1] > max_names:\n",
    "        piv = piv.sample(max_names, axis=1, random_state=0)\n",
    "    C = piv.corr().values\n",
    "    iu = np.triu_indices(C.shape[0], 1)\n",
    "    v = C[iu]; v = v[~np.isnan(v)]\n",
    "    return v.mean() if len(v) else np.nan\n",
    "\n",
    "months = sorted(m['ym'].unique())\n",
    "recs = []\n",
    "for t in months:\n",
    "    snap = m[m.ym == t]\n",
    "    W = snap[snap.decile == N_DECILES].ticker.values\n",
    "    L = snap[snap.decile == 1].ticker.values\n",
    "    if len(W) < 10 or len(L) < 10: continue\n",
    "    wlo = (t.to_timestamp() - pd.DateOffset(months=FORM_MONTHS)).to_period('W')\n",
    "    whi = t.to_timestamp().to_period('W')\n",
    "    win = weekly[(weekly.yw >= wlo) & (weekly.yw <= whi)]\n",
    "    cW = pair_corr(W, win); cL = pair_corr(L, win)\n",
    "    if not (np.isnan(cW) and np.isnan(cL)):\n",
    "        recs.append((t, np.nanmean([cW, cL])))\n",
    "com = pd.DataFrame(recs, columns=['ym','comom']).dropna()\n",
    "print('serie comomentum:', com.shape, '| media=%.3f' % com.comom.mean())\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 7 -- TEST DE FASE: alto comomentum -> reversion (CICLO)\n",
    "wml = (m[m.decile==N_DECILES].groupby('ym')['ret'].mean()\n",
    "       - m[m.decile==1].groupby('ym')['ret'].mean()).rename('wml').reset_index()\n",
    "wml = wml.sort_values('ym').reset_index(drop=True)\n",
    "wml['fwd12'] = wml['wml'].rolling(12).mean().shift(-12)\n",
    "wml['fwd24'] = wml['wml'].rolling(24).mean().shift(-24)\n",
    "mm = com.merge(wml, on='ym', how='inner').dropna(subset=['comom'])\n",
    "mm['q'] = pd.qcut(mm['comom'], 5, labels=False) + 1\n",
    "tab = mm.groupby('q')[['wml','fwd12','fwd24']].mean()*100\n",
    "print('Retorno momentum por quintil de comomentum (%/mes):')\n",
    "print(tab.to_string())\n",
    "hi = mm[mm.q==5]; lo = mm[mm.q==1]\n",
    "for h in ['fwd12','fwd24']:\n",
    "    a, b = hi[h].dropna(), lo[h].dropna()\n",
    "    tt = st.ttest_ind(a, b, equal_var=False)\n",
    "    print(f'{h}: alto={a.mean()*100:+.3f}%  bajo={b.mean()*100:+.3f}%  '\n",
    "          f'diff={(a.mean()-b.mean())*100:+.3f}%  t={tt.statistic:+.2f} p={tt.pvalue:.1e}')\n",
    "print('\\nTEORIA: alto comomentum -> fwd menor (reversion=ciclo); bajo -> estable.')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 8 -- FIGURAS\n",
    "fig,ax=plt.subplots(figsize=(3.6,2.6))\n",
    "ax.plot(com.ym.dt.to_timestamp(), com.comom, color='0.2', lw=0.8)\n",
    "ax.set_xlabel('fecha'); ax.set_ylabel('comomentum (corr media)')\n",
    "ax.set_title('Comomentum (Stooq US)', fontsize=9, loc='left')\n",
    "fig.tight_layout(); fig.savefig('/content/real_fig_comomentum.pdf'); plt.show()\n",
    "\n",
    "fig,ax=plt.subplots(figsize=(3.4,2.6))\n",
    "ax.bar(tab.index, tab['fwd12'], color='0.4', width=0.6); ax.axhline(0,color='0.6',lw=0.6)\n",
    "ax.set_xlabel('quintil comomentum (1=bajo,5=alto)')\n",
    "ax.set_ylabel('momentum fwd 12m (%/mes)')\n",
    "ax.set_title('Estable abajo, reversion arriba', fontsize=9, loc='left')\n",
    "fig.tight_layout(); fig.savefig('/content/real_fig_phase.pdf'); plt.show()\n",
    "print('figuras en /content')\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": [],
   "source": [
    "# %% CELL 9 -- RESULTS BLOCK\n",
    "print('='*64); print('PEGAME ESTE BLOQUE ENTERO'); print('='*64)\n",
    "print(f'source                = Stooq_US_daily')\n",
    "print(f'span                  = {px.date.dt.year.min()}-{px.date.dt.year.max()}')\n",
    "print(f'n_tickers             = {px.ticker.nunique()}')\n",
    "print(f'top_liquid_universe   = {TOP_LIQUID}')\n",
    "print(f'comom_n_months        = {len(com)}')\n",
    "print(f'comom_mean            = {com.comom.mean():.4f}')\n",
    "print(f'comom_min             = {com.comom.min():.4f}')\n",
    "print(f'comom_max             = {com.comom.max():.4f}')\n",
    "for q in range(1,6):\n",
    "    if q in tab.index:\n",
    "        r=tab.loc[q]; print(f'q{q}_wml={r[\"wml\"]:+.4f}  fwd12={r[\"fwd12\"]:+.4f}  fwd24={r[\"fwd24\"]:+.4f}')\n",
    "for h in ['fwd12','fwd24']:\n",
    "    a,b=hi[h].dropna(),lo[h].dropna(); tt=st.ttest_ind(a,b,equal_var=False)\n",
    "    print(f'{h}_hi_minus_lo_pctmo = {(a.mean()-b.mean())*100:.4f}')\n",
    "    print(f'{h}_t = {tt.statistic:.3f}   {h}_p = {tt.pvalue:.3e}')\n",
    "print('='*64)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}